version: '2.4'

networks:
  docker-compose-network:
    driver: bridge

services:
  api:
    build: .
    image: pismo-case:latest
    container_name: "api"
    depends_on:
      - mongodb_pismo
    environment:
      MONGODB_HOSTNAME: mongodb_pismo
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-compose-network

  mongodb_pismo:
    image: mongo:latest
    container_name: "mongodb_pismo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017
    command: mongod
    networks:
      - docker-compose-network